In [15]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import Layer

To create tensors that can be updated (weights) we use : Variable , because the other tensors are constant 

In [2]:
x = tf.Variable(initial_value=tf.random.normal(shape=(2,1), mean=0 , stddev=0.1))
print(x)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-0.0320435 ],
       [-0.06465375]], dtype=float32)>


2025-09-15 13:38:09.189789: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2025-09-15 13:38:09.189811: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:178] verbose logging is disabled. Rerun with verbose logging (usually --v=1 or --vmodule=cuda_diagnostics=1) to get more diagnostic output from this module
2025-09-15 13:38:09.189815: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:183] retrieving CUDA diagnostic information for host: pepito
2025-09-15 13:38:09.189817: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:190] hostname: pepito
2025-09-15 13:38:09.189881: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:197] libcuda reported version is: 550.163.1
2025-09-15 13:38:09.189893: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:201] kernel reported version is: 550.163.1
2025-09

In [3]:
#And now we can modify the variable with the .assign method
x[0 , 0].assign(3.0)
x[0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

We also have some classic math operation : sqrt,square, id matrice , product

In [4]:
a = tf.ones((2,2))
b = tf.square(a)
c = tf.sqrt(b)
print(a)
print(b)
print(c)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


Now let's talk about the tape . In a tape , everything is kinda recorded . If we do some operations on a tensor , these operations are kept in the tape and allows tensorflow to calculate the gradient more quickly and efficiently.

In [5]:
# Here is an example
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x**2

grad = tape.gradient(y,x)
print(grad)

tf.Tensor(6.0, shape=(), dtype=float32)


We can also use a nested structure where we can compute second-order gradients or more 

In [6]:
time = tf.Variable(0.)
with tf.GradientTape() as first_tape:
    with tf.GradientTape() as second_tape:
        position = 5.0 *time**2
    speed = second_tape.gradient(position,time)
acceleration = first_tape.gradient(speed, time)

print(speed)
print(acceleration)

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(10.0, shape=(), dtype=float32)


Keras 

A Layer is an object that encapsulates some state (weights) and some computation
(a forward pass). The weights are typically defined in a build() (although they could
also be created in the constructor, __init__()), and the computation is defined in
the call() method.

In [16]:
class SimpleDense(tf.keras.layers.Layer):
    
    def __init__(self,units,activation = None):
        super().__init__()
        self.units = units
        self.activation = activation
        
    def build(self,input_shape):
        input_dim = input_shape[-1]
        self.W = self.add_weight(shape=(input_dim,self.units), initialize = "random_normal")
        self.b = self.add_weight(shape = (self.units,), initialiazer = "zeros")
    
    def call(self,inputs):
        y= tf.matmul(inputs, self.W)
        if self.activation is not None:
            y = self.activation(y)
        return y

Let see how to use keras API to buil a Simple NN

In [18]:
from tensorflow.python.keras import layers
from tensorflow.python.keras import models

In [27]:
#Here we use a simple sequantial architecture with two layers
model = models.Sequential([
    layers.Dense(32,activation="relu"),
    layers.Dense(32)
])

#Use .compile method to configure the trainning process
model.compile()

To monitor the loss we use the .fit() method